# Generated by Django 5.2.1 on 2025-05-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mn', '0002_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
